# -*- coding: utf-8 -*-
"""Metode_Matriks_balikan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXV1AjwxDDc09S9UgHF01qwpRL9EC41c

Gina Nabila 21120122130055

Metode Numerik Kelas D
"""

import numpy as np
def solve_linear_system(A, B):
    """
    Menyelesaikan Sistem Persamaan Linear Ax = B dengan metode matriks balikan.
    A: Matriks koefisien (n x n)
    B: Vektor hasil (n x 1)
    """
    try:
        # Perhitungan matriks balikan A
        A_inv = np.linalg.inv(A)

        # Perkalian matriks balikan A dengan vektor hasil B
        X = np.dot(A_inv, B)

        return X
    except np.linalg.LinAlgError:
        return None  # Matriks A tidak memiliki balikan

A = np.array([[3, 2], [2, 1]])
B = np.array([[6], [5]])

# Penyelesaian sistem persamaan linear
solution = solve_linear_system(A, B)

if solution is not None:
    x, y = solution.flatten()
    print(f"Solusi persamaan : x = {x}, y = {y}")
else:
    print("Matriks koefisien tidak memiliki balikan.")

# Code Testing
# Verifikasi solusi dengan mengalikan matriks A dengan solusi yang ditemukan
if np.allclose(np.dot(A, solution), B):
    print("Verifikasi berhasil: A * X = B")
else:
    print("Verifikasi gagal.")